packages/@contentlayer/utils/src/node/fs.ts
That PR adds an `rm` function to the `fs` module
=> add rm function to the fs module

packages/contentlayer/README.md
Just created my personal site using contentlayer, it's been really good experience.
=> docs: added a new user to README

packages/contentlayer/README.md
This PR adds my website to the readme file.
=> Add my website to the readme

packages/contentlayer/README.md
Hi Maintainers👋
Thank you so much for your awesome work. I love contentlayer!
I tried it out on my website [dawchihliou.github.io](https://github.com/DawChihLiou/dawchihliou.github.io). It would be great to be part of your showcase. Thank you so much.
- `packages/contentlayer/README.md`
=> docs: add dawchihliou.github.io in README.md

.gitmodules
A temporary fix for the ODD issue as discussed on [Discord](https://canary.discord.com/channels/816244985187008514/816246578594840586/938082102455468042)
=> refactor(gitmodules): A workaround to not delete files in git-submod dir

.gitmodules
Reverts contentlayerdev/contentlayer#107
=> Revert "refactor(gitmodules): A workaround to not delete files in git-submod dir"

packages/contentlayer/README.md
Fixed the previously requested changes. Hope this is fine!
=> Add myself to README.md

packages/contentlayer/README.md
Hello! Just added my website to the list. :)
=> add alpesdream.vercel.app to the readme.md list

packages/contentlayer/README.md
Hi. I added my blog using contentlayer to the list at the end.
=> Adding my website to README.md

packages/contentlayer/README.md
Adds a website I built with contentlayer.
=> Add Website to README

packages/contentlayer/README.md
I created a website provides list of handy and easy to understand snippets that help boost developer productivities e.g turn any website into dark mode, save json as file, add any remote library code to current page, etc
This was built with Contentlayer ;)
https://scriptbar-snippets.tryapp.us/
=> add scriptbar snippets

packages/contentlayer/README.md
I have just rewritten all of my website with TypeScript, MDX and Contentlayer. Really love how easy I can do with Contentlayer
Really excited to add my website to README.md
=> Add my website to README.md

packages/contentlayer/README.md
I'm happy to be among earlier ContentLayer adopters. 
It took me a while to develop a new personal website, but I'm honestly using CL since February 1st, 2022.
Unfortunately, it's not open-source.
=> Add additional website to the list

packages/contentlayer/README.md
Huge fan of Contentlayer and wanted to add my website to show my support—keep up the great work!!
=> Added the website of Nicholas Warren

packages/contentlayer/README.md
Note that there are links in here that will be broken until the website is launched.
=> Update readme for beta launch

packages/contentlayer/README.md
Thank you so much for your work with Contentlayer. I am loving Contentlayer!
I am using it for my website too and I would love to be a part of your showcase. Thanks!
=> Added achintyajha.com to README.md

packages/contentlayer/README.md
Awesome work on `contentlayer`! I have been using it for a while. I added my blog powered by `contentlayer` ✨
It is not (yet) open source. Nonetheless, I am working on a series of posts about `contentlayer` ([preview](https://github.com/SandroMaglione/nextjs-contentlayer-blog-template)).
Thanks for your awesome work 🙏🏼
=> Updated README "who is using contentlayer"

packages/contentlayer/README.md
Had a DIY solution in the past, but this is above anything else. Great job, and thanks for this awesome project!
=> Add `cretu.dev` to README.md

packages/contentlayer/README.md
I recently migrated to `contentlayer` from DIY solution and it felt great to remove a lot of code. awesome project!
=> Add `jarocki.me` to README.md

packages/contentlayer/README.md
Awesome work on contentlayer! I have been using it for a while. I added my blog powered by contentlayer ✨
Thanks 😊
=> Add iyansr.id to README

packages/contentlayer/README.md
Contentlayer is an amazing stuff. This is fast, fun, and easy to use. I love the way “content into data” model! ✨
=> Add gipsterya.com to README.md

packages/contentlayer/README.md
contentlayer is awesome project! This is really helpful to construct my blog. 👍👍👍
I really appreciate to developer in contentlayer.
If I have a chance, I will contribute to the project. 💪
=> Add kyoung-jnn.com to README.md

packages/contentlayer/README.md
=> 👋 Add MrCatDev page

packages/contentlayer/README.md
- https://igorkowalczyk.dev
- https://github.com/igorkowalczyk/igorkowalczyk.github.io
=> Add igorkowalczyk.dev to README

packages/contentlayer/README.md
Add to entry list: __Who is using Contentlayer?__
=> Add christianpenrod.com

packages/contentlayer/README.md
=> add xahidex.com

packages/contentlayer/README.md
Kindly add my [website](https://heykapil.in) to readme!
=> Added heykapil.in

packages/contentlayer/README.md
The POG (Programação Orientada a Gambiarra) is a book about Workaround Oriented Programming (WOP). This book has the intent to speak about errors, bad practices, and code smell, with humor.
=> Update README.md - adding livropog.com.br

packages/contentlayer/README.md
Adding my project https://adrianmato.art
=> add: adrianmato.art to README

packages/next-contentlayer/src/hooks/useMDXComponent.ts
=> improve useMDXComponent return type

packages/contentlayer/README.md
=> docs(readme): update sitelist

packages/contentlayer/README.md
I'm doing git integrations with contentlayer: https://github.com/contentlayerdev/contentlayer/discussions/345
=> Add soapbox.pub to README

packages/@contentlayer/source-files/package.json, packages/@contentlayer/source-files/src/__test__/errors/aggregate.spec.ts, packages/@contentlayer/source-files/src/__test__/errors/utils.ts, yarn.lock
Superseds #367
Thanks a lot @feliskio
=> chore: replace faker library with @faker-js/faker

packages/contentlayer/README.md
My website [nikhilmohite.com](https://nikhilmohite.com) is using contentlayer to manage blogs.
=> Add nikhilmohite.com

packages/contentlayer/README.md
Adding my personal blog https://shenlu.me, which using contentlayer to manage the content of it.
=> Add shenlu.me to README

packages/contentlayer/README.md
Adding my personal blog https://chillinmice-dev.vercel.app/, which using contentlayer to manage the content of it.
=> Add chillinmice.dev to README

packages/contentlayer/README.md
This PR adds a link to [jasongerbes.com](https://jasongerbes.com) to the README file.
=> Add jasongerbes.com to README

packages/contentlayer/README.md
I'm loving contentlayer @schickling !  great work!
=> Irregular-expression.com is using contentlayer

packages/contentlayer/README.md
Hey, here is a PR adding my blog to the contentlayer README.
**Changes**: Adds the blog link and source to the README.
Please let me know if there are any changes.
=> docs: add justgokul.dev to readme

packages/contentlayer/README.md
Update from `mateusf.vercel.app` to `mateusf.com`
=> Update "Who is using" domain

packages/contentlayer/README.md
Hey there! 👋
I've just added my portfolio as I'm using content layer for generating my blog and project files. :)
=> Update README.md with my website
